workspace = { members = ["operations"] }
[package]
name = "matrix-operations"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
name = "operations"
path = "operations/src/lib.rs"
[dependencies]
